version: "3.8"

services:
  # [Nginx] Reverse Proxy & Access Control Gateway
  # Nginx is Production-Only service
  nginx:
    build: ./backend/nginx
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app_network

  # [Backend] Production Overrides
  backend:
    image: rlaqudwn/rec-server:dev # or :latest
    restart: unless-stopped
    # No ports exposed to host, only internal
    # No volumes (code inside image)

    # Environment Overrides (Injected via .env file on server)
    environment:
      - GCS_KEY_BASE64=${GCS_KEY_BASE64}
      - STEAM_API_KEY=${STEAM_API_KEY}

  # [Monitoring] cAdvisor (Container Resource Usage)
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    # Ports not exposed to host, only accessible via internal network (Nginx)
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    devices:
      - /dev/kmsg
    restart: unless-stopped
    networks:
      - app_network
  # DB and Redis use Base config (no ports exposed)
