version: "3.8"

services:
  # [Nginx] ë¦¬ë²„???„ë¡??ë°??‘ê·¼ ?œì–´ ê²Œì´?¸ì›¨??
  # Nginx???´ì˜(Production) ?˜ê²½?ì„œë§??¤í–‰?©ë‹ˆ??
  nginx:
    build: ./backend/nginx
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app_network

  # [Backend] ?´ì˜ ?˜ê²½ ?„ìš© ?¤ì •
  backend:
    build:
      context: .
      target: runner
    image: ${DOCKER_USERNAME}/rec-server:latest
    restart: unless-stopped
    # ?¸ìŠ¤???¬íŠ¸ ?¸ì¶œ ?†ìŒ, ?´ë? ?¤íŠ¸?Œí¬ë§??¬ìš©
    # ë³¼ë¥¨ ë§ˆìš´???†ìŒ (?´ë?ì§€ ?´ë? ì½”ë“œ ?¬ìš©)

    # ?˜ê²½ ë³€???¤ë²„?¼ì´??(?œë²„??.env ?Œì¼?ì„œ ì£¼ì…??
    env_file:
      - ./.env
    environment:
      - GCS_KEY_BASE64=${GCS_KEY_BASE64}
      - STEAM_API_KEY=${STEAM_API_KEY}

  # [Monitoring] cAdvisor (ì»¨í…Œ?´ë„ˆ ë¦¬ì†Œ???¬ìš©??ëª¨ë‹ˆ?°ë§)
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    command: ["/usr/bin/cadvisor", "--url_base_prefix=/monitor"]
    # ?¸ìŠ¤???¬íŠ¸ ?¸ì¶œ ???? ?¤ì§ ?´ë? ?¤íŠ¸?Œí¬(Nginx)ë¥??µí•´?œë§Œ ?‘ê·¼ ê°€??
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    devices:
      - /dev/kmsg
    restart: unless-stopped
    networks:
      - app_network
  # DB?€ Redis??Base ?¤ì •??ê·¸ë?ë¡??¬ìš© (?¸ë? ?¬íŠ¸ ?¸ì¶œ ?†ìŒ)
