version: "3.8"

services:
  # [Backend] 백엔드 공통 설정
  backend:
    image: rec-server # 임시 이미지 이름, prod/dev에서 오버라이드
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - app_network
    environment:
      - DEBUG_MODE=True # 개발 환경: True, 프로덕션: False

  db:
    image: pgvector/pgvector:pg15
    ports:
      - "5432:5432"
    volumes:
      # [DB] PostgreSQL 공통 설정
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-mypassword}
      - POSTGRES_DB=${POSTGRES_DB:-postgres}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-postgres}" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app_network

  redis:
    image: redis:alpine
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app_network

volumes:
  postgres_data:


networks:
  app_network:
    driver: bridge
