"""init_mvp_schema

Revision ID: 04606b955656
Revises: 
Create Date: 2026-02-03 09:02:00.054525

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '04606b955656'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_games_embedding_hnsw'), table_name='games', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    op.drop_index(op.f('idx_games_genres_kr_gin'), table_name='games', postgresql_using='gin')
    op.drop_index(op.f('idx_games_supported_languages_gin'), table_name='games', postgresql_using='gin')
    op.drop_index(op.f('idx_games_tags_en_gin'), table_name='games', postgresql_using='gin')
    op.drop_index(op.f('ix_games_app_id'), table_name='games')
    op.drop_index(op.f('ix_games_id'), table_name='games')
    op.drop_index(op.f('ix_games_name'), table_name='games')
    op.drop_table('games')
    op.add_column('conversations', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.create_index(op.f('ix_conversations_conversation_id'), 'conversations', ['conversation_id'], unique=False)
    op.alter_column('messages', 'role',
               existing_type=postgresql.ENUM('USER', 'AI', 'SYSTEM', name='messagerole'),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.create_index(op.f('ix_messages_conversation_id'), 'messages', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_messages_created_at'), 'messages', ['created_at'], unique=False)
    op.create_index(op.f('ix_messages_message_id'), 'messages', ['message_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messages_message_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_created_at'), table_name='messages')
    op.drop_index(op.f('ix_messages_conversation_id'), table_name='messages')
    op.alter_column('messages', 'role',
               existing_type=sa.String(length=20),
               type_=postgresql.ENUM('USER', 'AI', 'SYSTEM', name='messagerole'),
               existing_nullable=False)
    op.drop_index(op.f('ix_conversations_conversation_id'), table_name='conversations')
    op.drop_column('conversations', 'updated_at')
    op.create_table('games',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('app_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('price', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('currency', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('release_date', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('short_description_kr', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('short_description_en', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('genres_kr', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('genres_en', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('header_image', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('screenshots', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('movies', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('specs', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('supported_languages', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('tags_en', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('categories', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('context', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('games_pkey'))
    )
    op.create_index(op.f('ix_games_name'), 'games', ['name'], unique=False)
    op.create_index(op.f('ix_games_id'), 'games', ['id'], unique=False)
    op.create_index(op.f('ix_games_app_id'), 'games', ['app_id'], unique=True)
    op.create_index(op.f('idx_games_tags_en_gin'), 'games', ['tags_en'], unique=False, postgresql_using='gin')
    op.create_index(op.f('idx_games_supported_languages_gin'), 'games', ['supported_languages'], unique=False, postgresql_using='gin')
    op.create_index(op.f('idx_games_genres_kr_gin'), 'games', ['genres_kr'], unique=False, postgresql_using='gin')
    op.create_index(op.f('idx_games_embedding_hnsw'), 'games', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    # ### end Alembic commands ###
