gcs:
  bucket_name: "data-tailor-test"
  project_id: "pro-recsys-finalproject-recsys-05"


# 로컬 데이터 기본 경로 (스크립트 실행 위치 기준)
# - raw/: 원본 데이터
# - processed/: 가공된 데이터
# - models/: 학습된 모델
local:
  data_root: "app/data"      # 로컬 데이터 폴더 (backend/app/data)
  files:
    games_metadata.jsonl:
      local_path: "processed/games_metadata.jsonl"       # 로컬 파일명 (data_root 기준)
      upload_path: "processed/games_metadata.jsonl"
      download_path: "processed/games_metadata.jsonl"

    item_similarity.pkl:
      local_path: "item_similarity.pkl"
      upload_path: "ml_rec/item_similarity.pkl"
      download_path: "ml_rec/item_similarity.pkl"

versioning:
  use_timestamp: false    # 업로드 시 파일명에 타임스탬프 자동 추가
  timestamp_format: "%Y%m%d_%H%M%S"
